name: "sgdemux"
description: Demultiplex bgzip'd fastq files
keywords:
  - demultiplex
  - fastq
tools:
  - "sgdemux":
      description: "Tool for demultiplexing sequencing data generated on Singular Genomics' sequencing instruments."
      homepage: "https://github.com/Singular-Genomics/singular-demux"
      documentation: "https://github.com/Singular-Genomics/singular-demux"
      licence: "['For Singular G4™ Sequencing Platform only']"

input:
- meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - run_manifest:
      type: file
      description: RunManifest file
      pattern: "*.{csv}"
  - run_dir:
      type: directory
      description: "Input run directory containing optionally containing a RunManifest.json if run_manifest is not supplied"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - sample_fastq:
      type: file
      description: Demultiplexed sample FASTQ files
      pattern: "output/*/*/*_R*.fastq.gz"
  - metrics:
      type: file
      description: Sample metrics
      pattern: "output/metrics.csv"
  - most_frequent_unmatched:
    type: file
    description: Unmatched Sequences
    pattern: "output/most_frequence_unmatched.tsv"
  - per_project_metrics:
      type: file
      description: Metrics Per Project
      pattern: "output/per_project_metrics.tsv"
  - per_sample_metrics:
    type: file
    description: Matrics Per Sample
    pattern: "output/per_sample_metrics.tsv"
  - sample_barcode_hop_metrics:
    type: file
    description: Metrics Per Sample Barcode Hop
    pattern: "output/sample_barcode_hop_metrics/tsv"


authors:
  - "@samfulcrum"
